import { ReviewTag } from "./ReviewTag";

type ReviewTagMetadataInput = Omit<ReviewTag, "id" | "timestamp" | "dedupeKey">;

export const REVIEW_TAG_METADATA: Record<string, ReviewTagMetadataInput> = {
  "SSN Miskey": {
    tag: "SSN Miskey",
    group: "identity",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Watchlist Review": {
    tag: "Watchlist Review",
    group: "compliance",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Phone Review": {
    tag: "Phone Review",
    group: "identity",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "KYC Approved": {
    tag: "KYC Approved",
    group: "workflow",
    severity: "low",
    direction: "positive",
    requiresReview: false,
    canContributeToDecline: false,
  },
  "Fraud Review": {
    tag: "Fraud Review",
    group: "fraud",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Denied Fraud": {
    tag: "Denied Fraud",
    group: "fraud",
    severity: "high",
    direction: "negative",
    requiresReview: false,
    canContributeToDecline: true,
  },
  "TU Credit Manual Review": {
    tag: "TU Credit Manual Review",
    group: "credit",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "TU Credit Denied": {
    tag: "TU Credit Denied",
    group: "credit",
    severity: "high",
    direction: "negative",
    requiresReview: false,
    canContributeToDecline: true,
  },
  "TU Credit Approved": {
    tag: "TU Credit Approved",
    group: "credit",
    severity: "low",
    direction: "positive",
    requiresReview: false,
    canContributeToDecline: false,
  },
  "SSN Warning": {
    tag: "SSN Warning",
    group: "identity",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "High Fraud Risk": {
    tag: "High Fraud Risk",
    group: "fraud",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "Medium Fraud Risk": {
    tag: "Medium Fraud Risk",
    group: "fraud",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "SSN Velocity Warning": {
    tag: "SSN Velocity Warning",
    group: "fraud",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Email Address Velocity Warning": {
    tag: "Email Address Velocity Warning",
    group: "fraud",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Velocity Warning": {
    tag: "Velocity Warning",
    group: "fraud",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Address Warning": {
    tag: "Address Warning",
    group: "identity",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "DOB Miskey": {
    tag: "DOB Miskey",
    group: "identity",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Phone Match": {
    tag: "Phone Match",
    group: "identity",
    severity: "low",
    direction: "positive",
    requiresReview: false,
    canContributeToDecline: false,
  },
  "Watchlist Warning": {
    tag: "Watchlist Warning",
    group: "compliance",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Adverse Media": {
    tag: "Adverse Media",
    group: "compliance",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "PEP Match": {
    tag: "PEP Match",
    group: "compliance",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "High Synthetic Fraud Risk": {
    tag: "High Synthetic Fraud Risk",
    group: "fraud",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "Medium Synthetic Fraud Risk": {
    tag: "Medium Synthetic Fraud Risk",
    group: "fraud",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Email Warning": {
    tag: "Email Warning",
    group: "identity",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Deceased Warning": {
    tag: "Deceased Warning",
    group: "identity",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "KYC Review": {
    tag: "KYC Review",
    group: "identity",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "SSN on Denylist": {
    tag: "SSN on Denylist",
    group: "identity",
    severity: "high",
    direction: "negative",
    requiresReview: false,
    canContributeToDecline: true,
  },
  "Bank Account Status Invalid": {
    tag: "Bank Account Status Invalid",
    group: "bank",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "Bank Account Ownership Unknown": {
    tag: "Bank Account Ownership Unknown",
    group: "bank",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Bank Account Ownership Mismatch": {
    tag: "Bank Account Ownership Mismatch",
    group: "bank",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "Bank Account Ownership Match": {
    tag: "Bank Account Ownership Match",
    group: "bank",
    severity: "low",
    direction: "positive",
    requiresReview: false,
    canContributeToDecline: false,
  },
  "Open Liens Found": {
    tag: "Open Liens Found",
    group: "business",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Bankruptcy 36 months": {
    tag: "Bankruptcy 36 months",
    group: "business",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "Litigations Found": {
    tag: "Litigations Found",
    group: "business",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Secretary of State Match": {
    tag: "Secretary of State Match",
    group: "business",
    severity: "low",
    direction: "positive",
    requiresReview: false,
    canContributeToDecline: false,
  },
  "FEIN Unmatched": {
    tag: "FEIN Unmatched",
    group: "business",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "FEIN Document Required": {
    tag: "FEIN Document Required",
    group: "business",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Business Address Matched": {
    tag: "Business Address Matched",
    group: "business",
    severity: "low",
    direction: "positive",
    requiresReview: false,
    canContributeToDecline: false,
  },
  "Address Not Verified": {
    tag: "Address Not Verified",
    group: "business",
    severity: "medium",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: false,
  },
  "Business Name Matched": {
    tag: "Business Name Matched",
    group: "business",
    severity: "low",
    direction: "positive",
    requiresReview: false,
    canContributeToDecline: false,
  },
  "Business Name Unmatched": {
    tag: "Business Name Unmatched",
    group: "business",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "Secret of State Status Inactive/Unknown": {
    tag: "Secret of State Status Inactive/Unknown",
    group: "business",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "Secret of State Unmatched": {
    tag: "Secret of State Unmatched",
    group: "business",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
  "High Risk Industry": {
    tag: "High Risk Industry",
    group: "business",
    severity: "high",
    direction: "negative",
    requiresReview: true,
    canContributeToDecline: true,
  },
};